### PR TITLE
Updating nomad version to 0.8.0

### PR DESCRIPTION
**Pull request by xmackex**
Due to recent Nomad release would be nice to update dep

### CODE REVIEW

**Comment by jrasell** [comment]
hi @xmackex thanks for the PR. Is there a requirement to update the Nomad dependency?

**Comment by xmackex** [comment]
Hi @jrasell fortunately now (as far as I fount)

I just updated Nomad, ran Levant and got some errors, only after I've updated dep and tested with new binary I have discovered that when I updated Nomad I have not restarted it. So both old and new version of lib working.

Potentially there can be issues with job validation due to Hashicorp have introduced one new stanza and updated several of old (`check_restart`)

**Comment by jrasell** [comment]
OK that makes sense.

Alongside this, could you please raise an issue against the project detailing the issue you're facing, it will help me make sure the 0.8.0 release has not caused any other issues.

**Comment by xmackex** [comment]
Due to my mistake I identified issue in wrong way. So now there is no issue. Just cause I've already build it locally with new version I've decided to make a PR.

Sorry if this is wrong way, unfortunately don't have much experience with OpenSource development.

**Comment by jrasell** [comment]
OK. I will hold this until 0.1.1 and do some testing as I want to get 0.1.0 out today or tomorrow.

**Comment by jrasell** [comment]
Update - I will push this out now as part of 0.1.0

**Pull request merged**
