### PR TITLE
Add `env` function similar to consul-template

### PR DESCRIPTION
**Pull request by leprechau**

### CODE REVIEW

**Comment by leprechau** [comment]
@jrasell It's a mercurial file (https://www.mercurial-scm.org/wiki/DirState).  I think GoLand indexed that directory and wrote the dirstate.  I'll add that to the ignore.

**Comment by leprechau** [comment]
So I'm not sure I should ignore those files ... they are part of the mercurial structure along with the `cache` folder.  Since the entire vendor directory is checked into the repo the contents of the `dirstate` and `cache` folder may change anytime someone indexes those files.  What do you want to do?

**Comment by leprechau** [comment]
For instance, my current `git status` looks like this ...
```text
ahurt1:levant ahurt$ git status
On branch feature/add-env-func
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.idea/
	vendor/github.com/hashicorp/go-getter/test-fixtures/basic-hg/.hg/cache/checkisexec
	vendor/github.com/hashicorp/go-getter/test-fixtures/basic-hg/.hg/cache/checklink
	vendor/github.com/hashicorp/go-getter/test-fixtures/basic-hg/.hg/cache/checklink-target
	vendor/github.com/hashicorp/go-getter/test-fixtures/basic-hg/.hg/cache/checknoexec
	vendor/github.com/hashicorp/go-getter/test-fixtures/basic-hg/.hg/cache/tags2-visible
	vendor/github.com/hashicorp/terraform/config/module/test-fixtures/basic-hg/.hg/cache/checkisexec
	vendor/github.com/hashicorp/terraform/config/module/test-fixtures/basic-hg/.hg/cache/checklink
	vendor/github.com/hashicorp/terraform/config/module/test-fixtures/basic-hg/.hg/cache/checklink-target
	vendor/github.com/hashicorp/terraform/config/module/test-fixtures/basic-hg/.hg/cache/checknoexec
	vendor/github.com/hashicorp/terraform/config/module/test-fixtures/basic-hg/.hg/cache/tags2-visible

nothing added to commit but untracked files present (use "git add" to track)
```

The reason the `dirstate` files showed as changed is they are already in the git history and the `cache/*` files are not.

**Comment by jrasell** [comment]
@leprechau I have never used mercurial so can't really comment but I would have a preference for avoiding these files as if they are just caching files they shouldn't be required.

**Comment by leprechau** [comment]
What do you think of just removing the `.hg` structure from under vendor?

**Comment by leprechau** [comment]
Okay, I ignored the `vendor/*/.hg/*` structure and reverted the `dirstate` files back to the master revision.

**Comment by stevenscg** [comment]
@leprechau Do you have some examples / use cases that you can include for this? I'm mostly looking for inspiration on how to use it.

**Comment by leprechau** [comment]
@stevenscg our use case is executing levant from within our Bamboo build system and using the exported environment variables from the build plan.

**Pull request merged**
